definitions:
  request.UserLogin:
    properties:
      password:
        type: string
      user_name_or_email:
        type: string
    type: object
  request.UserRegister:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  wrapper.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status_code:
        type: integer
      trace_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: API for get token from user name email and password
      parameters:
      - description: model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: API for get token from user name email and password
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Get my record page for non login usersas
      parameters:
      - description: model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/request.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: Get my record page for non login usersas
      tags:
      - user
swagger: "2.0"
